[ringstellum-config]
ringstellum=[ '@' , '{' , '/', 'K' ]

[plugboard-config]
plugboard=[ [ 4 , 54 ] , [ 90 , 24 ] , [ 5 , 75 ] , [84 , 31] ]

[reflector-config]
reflectors=["A","E","F","D"]

[rotor-config]
rotors=[ "I" ,  "V" ,  "VII"  , "IV" ]

[permutations-config]
permutations = 368

[text]
message="AAA"
target="n(Q"